### ISSUE TITLE
CSS文本溢出显示省略号

### ISSUE THREAD

**Issue by quxww1** [quxww1/blog#10]
# 单行溢出
```html
<div class="text">
    单行需要溢出的文本单行需要溢出的文本单行需要溢出的文本单行需要溢出的文本单行需要溢出的
</div>
```
```css
.text{
        overflow: hidden;
        text-overflow: ellipsis;
        white-space: nowrap;
        background-color: gray;
        width: 200px;
}
```
