### ISSUE TITLE
Vue中使用  css深度作用选择器

### ISSUE THREAD

**Issue by quxww1** [quxww1/blog#23]
> 昨天的需求 写下来记录一下

> 接口返回的html富文本数据，需要显示在页面上。但是vue里面就直接一个v-html就ok了，设置不了里面东西的样式。

> 所以 就去搜索了一波，发现了这么一句话：
![image](https://user-images.githubusercontent.com/22358674/50500827-b46a2600-0a8e-11e9-9733-243c797be13b.png)

 - 设置深度选择器
> 写法
```css
<style scoped>
.a >>> .b { /* ... */ }
</style>
```
> 有些像 Sass 之类的预处理器无法正确解析 >>>。这种情况下你可以使用 /deep/ 操作符取而代之——这是一个 >>> 的别名，同样可以正常工作。
```css
.a{
    /deep/ .b{

    }
  }
```

- 给v-html内容设置样式
```html
<!-- 内容区 -->
<div v-html="detail.info.content" class="content">
         {{detail.info.content}}
</div>
```
```css
.content {
    /deep/ img{
        width: 100%!important;
        height: auto!important;
    }
  }
```
